//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PNP.Services.Service.Services.GlobalSettings.SettingsFiles {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Database : global::System.Configuration.ApplicationSettingsBase {
        
        private static Database defaultInstance = ((Database)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Database())));
        
        public static Database Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DB\\Services.Unknown.db")]
        public string UnknownDB {
            get {
                return ((string)(this["UnknownDB"]));
            }
            set {
                this["UnknownDB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DB\\Services.History.db")]
        public string HistoryDB {
            get {
                return ((string)(this["HistoryDB"]));
            }
            set {
                this["HistoryDB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DB\\Modules.Pokemon.PokemonData.db")]
        public string PokemonDataDB {
            get {
                return ((string)(this["PokemonDataDB"]));
            }
            set {
                this["PokemonDataDB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DB\\Modules.Pokemon.PokemonMain.db")]
        public string PokemonMainDB {
            get {
                return ((string)(this["PokemonMainDB"]));
            }
            set {
                this["PokemonMainDB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DB\\Modules.Pokemon.TrainerData.db")]
        public string TrainerDataDB {
            get {
                return ((string)(this["TrainerDataDB"]));
            }
            set {
                this["TrainerDataDB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DB\\Modules.Pokemon.TrainerMain.db")]
        public string TrainerMainDB {
            get {
                return ((string)(this["TrainerMainDB"]));
            }
            set {
                this["TrainerMainDB"] = value;
            }
        }
    }
}
