// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PNP_Services.Databases.Core.HistoryDB;

namespace PNP_Services.Databases.Core.HistoryDB.Migrations
{
    [DbContext(typeof(HistoryContext))]
    partial class HistoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("PNP_Services.Databases.Core.HistoryDB.Model.HistoryEntry", b =>
                {
                    b.Property<Guid>("EntryGUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EntryTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntryValue")
                        .HasColumnType("TEXT");

                    b.HasKey("EntryGUID");

                    b.ToTable("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
