// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PNP_Services.Databases.Core.SettingDB;

namespace PNP_Services.Databases.Core.SettingDB.Migrations
{
    [DbContext(typeof(SettingContext))]
    [Migration("20210401122947_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("PNP_Services.Databases.SettingDB.Model.Setting", b =>
                {
                    b.Property<Guid>("SettingGUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("SettingEnum")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("SettingGUID");

                    b.ToTable("Settings");
                });
#pragma warning restore 612, 618
        }
    }
}
